steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/real-time-ingestor', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/real-time-ingestor']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - real-time-ingestor
      - --image=gcr.io/$PROJECT_ID/real-time-ingestor
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated
      - --service-account=835341756220-compute@developer.gserviceaccount.com
      - --set-env-vars=GCP_PROJECT=daring-atrium-454004-n4

timeout: 900s

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
